### PR TITLE
Added macros @process, @event, and @run!

### PR DESCRIPTION
**Pull request by hdavid16**
Had to preserve the `!` for `@run!` because `@run` clashes with VSCodeServer's `@run`.
Updated the first 3 examples to use these macros.
Did not create macros for `fun` or `Prc` because this would require adding a line before `@event` or `@process` to create the `fun` or `Prc`.
Did not include kwargs in the macros as macros do not accept kwargs. The only exception is `@event`, which can take as its last argument `n` for cases 3-5.

### CODE REVIEW

**Comment by pbayer** [comment]
Thank you Hector.

Wouldn't it be nicer still if someone could write:

```
@event clock arrive(clock, input, count) every Exponential(1/λ) 10
```
instead of
```
@event clock fun(arrive, clock, input, count) every Exponential(1/λ) 10
```
and
```
@process clock 1 serve(clock, i, input, output, Exponential(1/μ))
```
instead of
```
@process clock Prc(i, serve, i, input, output, Exponential(1/μ))
```

This would eliminate the need to use `fun` and `Prc` inside those macros. This would make the **macros really useful** because one could write the function call as later called by the event.

In this case e.g. the `arrive(clock, input, count)` had to be expanded to `fun(arrive, clock, input, count)` by the macro.
Maybe this is a little tricky since it should be able to produce nested `fun` calls. 

The @process macro would have to eliminate the first clock argument to serve. It should expand `1 serve(clock, i, input, output, Exponential(1/μ))` to `Prc(i, serve, i, input, output, Exponential(1/μ))`.

Is this possible? Wasn't something like that done for Julia 1.5.1 recently? I think, I read it in the release notes.

**Comment by pbayer** [comment]
or another way would be to eliminate one of the two clock arguments entirely, like that:

```
@event arrive(clock, input, count) every Exponential(1/λ) 10   # and
@process 1 serve(clock, i, input, output, Exponential(1/μ))
```

This would be still nicer! What do you think? Is this a dream?

**Comment by hdavid16** [comment]
Yes. I like it. I'll update the macros.

**Comment by hdavid16** [comment]
@pbayer what is the `1` you are referring to in `@process`?

**Comment by pbayer** [comment]
The 1 is the process id, a process gets registered with to the clock.processes dict.
It could be also a String and has to be unique.

So the @process 1 serve(clock, i, input, output, Exponential(1/μ))
would read “start process 1 with the serve function and those parameters”!

**Comment by pbayer** [comment]
What I remembered above was the `@ccall` macro mentioned in a [blogpost announcing Julia 1.5](https://julialang.org/blog/2020/08/julia-1.5-highlights/#new_ccall_macro). Maybe this helps.

**Comment by hdavid16** [comment]
Hi @pbayer. I've updated the macros as you suggested. Both expressions below work. The procedure you suggested that was used for `ccall` is actually the one used in SimJulia to define the `@process` macro for a `ResumableFunction`.

```julia
@event arrive(clock, input, count) every Exponential(1/λ) 10   # and
@process 1 serve(clock, i, input, output, Exponential(1/μ))
```

I've updated the first 3 examples. Please check and let me know what you think.

On another note, what are your thoughts on using a unique iterator to assign the `id` for a `process`? This is the approach used in SimJulia so the user does not need to specify the `id`, but it is auto-generated.

**Comment by pbayer** [comment]
Hi @hdavid16 the macros look great. I looked at the examples. With macros they get much cleaner. I‘m very much hooked 😊😅😂 and I will look into it more later.

Just some thoughts for now:

- This seems to become some sort of **comfort API** for DiscreteEvents,
- How about to add a `@cevent` macro for conditional events too?
- How about to add `@delay` and `@wait` macros? 

In the same direction it would make sense as you propose for the @process macro to auto-generate the id. The loop in the introductory example then would become:

```
for _ in 1:3      # start three server processes
    @process serve(clock, i, input, output, Exponential(1/μ))
end
```
This makes sense! Generally the id is needed only to identify a process within the `clk.processes` Dict if it has failed. But if you then get the stack trace for the task with `clk.processes[id].task`, usually it can be seen from the context what has gone wrong. So the id is not strongly needed. Also it is common practice in operating systems or communication protocols (e.g. OTP) to auto-generate PIDs and to return them on process creation. One way could be to implement that in `process!`, another to implement it in your new `@process` macro. What do you think?

Another thought goes into `Action`s. An `Action` in `DiscreteEvents` is defined as a `Function`, an `Expr` or a `Tuple` of them. Right now your `@event` macro accepts a function. This is enough for most cases. But what about the other cases? What do you think? For me It would make sense to leave that for now as you proposed. This would deprecate further the use of `Expr`  in favour of `Function`s. And tuples of functions can be easily replaced by one anonymous function calling a tuple of functions.

**Comment by pbayer** [comment]
Now I found that the functionality for dynamic PID identification is right there in `_register` (of process.jl).
I added `Prc(f, arg...; kw...)` and merged it into the PR. So `Prc` can be called without `id` and an integer id is then calculated dynamically during process startup (in `_register‘).

I would suggest then that you remove the first `id` argument from the `@process` macro as in my last comment and it should run. The processes then are registered with ids 1,2,3 in the intro.jl example. You can check it with `clock.processes`.

There is one thing yet missing from your `@process` macro: this is the `cycles` argument. It is needed if a process should only run a limited number of cycles. Could you please add it, similar to `n` in `@event`.

**Comment by hdavid16** [comment]
Hi @pbayer, I'll work on these. Could you point me to an example where an event takes an expression or a tuple?

**Comment by hdavid16** [comment]
I have added the `@delay` and `@wait` macros and updated the `@process` macro to accept `cycles`. I did not create the `@cevent` macro as `@event` will work for conditional events as well.

**Comment by pbayer** [comment]
> Hi @pbayer, ... Could you point me to an example where an event takes an expression or a tuple?

You can see examples mainly in two [notebooks on `DiscreteEventsCompanion`](https://github.com/pbayer/DiscreteEventsCompanion.jl/tree/master/examples/notebooks):

- Introduction to DiscreteEvents ([nbviewer link](https://nbviewer.jupyter.org/github/pbayer/DiscreteEventsCompanion.jl/blob/master/examples/notebooks/introduction.ipynb)) and
- Performance ([nbviewer link](https://nbviewer.jupyter.org/github/pbayer/DiscreteEventsCompanion.jl/blob/master/examples/notebooks/performance.ipynb))

As you see using expressions is deprecated for a reason but maybe practical in experimental work. 
Tuples are useful if you want to have more actions at the same time point. This is needed for discrete time simulations, conditional events and state machines

**Comment by pbayer** [comment]
> I have added the `@delay` and `@wait` macros and updated the `@process` macro to accept `cycles`. I did not create the `@cevent` macro as `@event` will work for conditional events as well.

Thank you, great !!! I will look at it and then merge.

**Comment by pbayer** [comment]
> ... `@event` will work for conditional events as well.

I cannot yet see how this should work, but I merge now and will figure it out. Thank you again.

**Comment by hdavid16** [comment]
> > ... `@event` will work for conditional events as well.
> 
> 
> 
> I cannot yet see how this should work, but I merge now and will figure it out. Thank you again.

I believe it should work since the conditional event! has a similar argument structure to the case #1 standard event!. Thus, instead of passing a time number, you would pass a condition and the appropriate method for event! would be called from the macro. If I am mistaken, let me know.

**Comment by hdavid16** [comment]
> > Hi @pbayer, ... Could you point me to an example where an event takes an expression or a tuple?
> 
> 
> 
> You can see examples mainly in two [notebooks on `DiscreteEventsCompanion`](https://github.com/pbayer/DiscreteEventsCompanion.jl/tree/master/examples/notebooks):
> 
> 
> 
> - Introduction to DiscreteEvents ([nbviewer link](https://nbviewer.jupyter.org/github/pbayer/DiscreteEventsCompanion.jl/blob/master/examples/notebooks/introduction.ipynb)) and
> 
> - Performance ([nbviewer link](https://nbviewer.jupyter.org/github/pbayer/DiscreteEventsCompanion.jl/blob/master/examples/notebooks/performance.ipynb))
> 
> 
> 
> As you see using expressions is deprecated for a reason but maybe practical in experimental work. 
> 
> Tuples are useful if you want to have more actions at the same time point. This is needed for discrete time simulations, conditional events and state machines
> 
> 

Can't we just run the macro in a loop to schedule several events? Or do you think it would be helpful to keep the Tuple input functionality?

**Comment by pbayer** [comment]
> Can't we just run the macro in a loop to schedule several events? 

No this is not possible nor for discrete time, nor for conditional events and state machines.

> Or do you think it would be helpful to keep the Tuple input functionality?

I don't think that the macro API could or should replace the extended API entirely. Now we can leave the macros for the common cases as they are and for the more special cases we can use the extended API (able to handle tuples and expressions).

Therefore I would explain the macros (mainly `@event` and `@process`) as convenience features in the documentation.

**Comment by hdavid16** [comment]
Sounds good

**Comment by pbayer** [comment]
now I updated the macros, documentation, integrated testing.
It's everything on master. I have yet to update the examples.

**Comment by hdavid16** [comment]
@pbayer , I think we may need to merge the two `@event` macros. The 1st case in `event!` would collide with the conditional `event!`, would it not? `@event f(args...) t` would be accepted by both versions of the macro. If it takes the conditional version, then an error would be thrown. I think we could just check if the second part of the macro is a `:call` or a `:tuple` to decide whether it is a conditional event or a normal event call. Would you agree?

**Comment by pbayer** [comment]
The @event macros use macro dispatch. For a conditional event there are two arguments to the macro. A timed event has more. The macro specializes to the conditional version if there are two arguments. The tests work well. So far I cannot see any collision.

**Comment by hdavid16** [comment]
Ok. I thought that the first case for event! would only require 2 arguments in the macro as well (the event function and the time).

**Comment by pbayer** [comment]
Yes there is one case where you can have a timed event with only one t argument (when we omit the timing argument). I will add this case to the 2-argument implementation.
> 
>

**Comment by pbayer** [comment]
I think calling explicitly `@event f(clk,b,c) t` **should be possible**. It would be an event at a fixed time. But it can be expressed more explicitly as `@event f(clk,b,c) at t` with the documented macro call, which I think is preferable. Therefore I will leave this possibility **undocumented**.

**Comment by pbayer** [comment]
After fiddling around with macros for some time I realise that there is yet more potential in it.

I would like if the `@event` macro supported anonymous functions for events too (not only for conditions). This would need to reintroduce the clock as a first argument.

Wouldn't it be nice if we could do something like
```
@event clk begin
    ... do something ...
    ... more ...
end every 5
```

What do you think? Can we develop this further, maybe for one of the next releases? Would it be worth the effort?

**Comment by hdavid16** [comment]
Sure! I'll take a crack at it next week or earlier if possible.

**Pull request merged**
